<a href="https://colab.research.google.com/github/Loris997/Assignment/blob/main/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#hide
! [ -e /content ] && pip install -Uqq fastbook
import fastbook
from fastai.vision.all import *
from fastbook import *
fastbook.setup_book()

# Introduction to Artificial Neural Networks

Please read the introdcution of neuronal networks of the book *Hands-On Machine Learning with Scikit-Learn, Keras & TensorFlow*, p. 299-316.

**Why have neural networks, even though they were invented early on, only now caught on?**

The first ANN was introduced in 1943. But back then deifferent reason hindered the success of it: 
- The computational power required to train neural networks was enormous
- There were not a lot of large enough datasets avalable

In the early 1980s, new architectures were invented
and better training techniques were developed, sparking a revival of interest in
connectionism, the study of neural networks. But progress was slow, and by the 1990s
other powerful machine learning techniques had been invented, such as support
vector machines. These other techiques were more promising and therefore ANNs were one again put on hold. 

The latest push comes because of the following reasons: 
- Huge quantity of data available to train neural networks
- ANNs frequently outperform other ML techniques on very large and complex
problems
- Tremendous increase in computing power
- Training algorithms have been improved
- Some theoretical limitations of ANNs have turned out to be benign in practice
- Some ANNs had success: now there is more funding and progress


**What is a perceptron and a threshold logic unit (TLU)?**

Threshold logic unit: The TLU computes a linear function of f its inputs: z =
w1 x1 + w2 x2 + ⋯ + wn xn + b = w⊺ x + b. After that it applies a step function to the result: hw(x) = step(z). The input weights are w and the bias term b.

Perceptron: A perceptron is composed of either one or more TLUs organizted in a single layer. Every TLU is connected to every output. 

**Try to define a linear function and a step function of your choice, use some values of your choice and explain what might be the result of the percepton. (maybe using max. two TLU's)**

We define a liner functions with two inputs x1 and x2: y = w1x1 + w2x2 + b, 
g = w3x1 * w4x2 + b2. 
We define both w1 and w2 as 0.5, w3 as 0.3 and w4 as 0.9. The bias b1 is set to 0.1 and b2 to 0.5. 
We use the Heaviside step function: Heaviside(z) =  0 if z < 0, 1 if z > 0. 

If we now feed the function with x1 = 2 and x2 = 1 the functions looks like this:

Y = 0.5 * 2 + 0.5 * 1 + 0.1
G = 0.3 * 2 + 0.9 * 1 + 0.5

Which results in the following output: y = 1.6 and g = 2.

1.6 > 0 and 2 > 0 therefore the Heaviside step function returns: 1 for both functions.

**What is a fully connected layer and a output layer?** 

Fully connected layer: When every TLU is connected to every output. 

Output layer: The last layer produces the output and is therefore output layer called.

**Why can we easily combine the equations of multiple instances into a fully connected layer?**

The mathematical operations in a fully connected layer are linear transformations, they can be expressed as matrix multiplication. Therefore it is possible to combine the equations of multiple instances into a fully connected layer. 
**What problem did Marvin Minsky and Seymour Paper highlight that perceptrons could not solve? What is a possible solution?**

They highlightet the exclusive OR (XOR) problem, which wasn't possible to be solved by perceptrons. 

A possible solution to the problem is multilayer perceptron. 

**What is a deep neuronal network?** 

If an ANN contains a deep stack of layers (hidden layers), it is called a deep neuronal network. In 1990 an ANN with two hidden layers was considered deep, nowadays there are ANNs with dozen or hundreds of layers. 

**What are hidden layers?** 

A perceptron contains always an input layer and an output layer. If there is another layer between these tow, this is called a hidden layer. 

**What means feedforward neural network (FNN).**

If the signal only flows in one direction, from the input to the output we talk of a feedforward neural network. 

**Try to explain how backpropagation works!**

Backpropagation can be defined in 6 steps:

- It handles one mini-batch at a time and goes through this set multiple times. Each pass is called an Epoch.
- Each mini-batch enters the network through the input layer. Then the algorithm copmputes the output of all neurons in the first hidden layer. This is repeted till each layer is through and we got the output of the output layer. This process is called the forward pass. 
- The algorithm measures the output error. 
- The algorithm computes how much each output bias and each connection to the output layer contributed to the error. 
- The algorithm then measures how much of these error contributions came from
each connection in the layer below. This process is done by working backwards till the input layer is reached. 
- The algorithm performs a gradient descent step to tweak all the connec‐
tion weights in the network.

**Why do we need activation functions, wouldn't it be easier just using linear functions?**

Activation functions are needed to add ninlinearity into the model. Without that, the neural network would only be a linear function of the input. This would limit the network and wouldn't be able to model complex relationships between input and output. 

## Ideas for the learning portfolio: 

1) For example, you could train a single TLU to classify iris flowers based on petal length and width in the !!!pyTorch!! environment.

2) You could add to our king county housepricing ML project a neuronal network and compare it to the other models. 

In [ ]:
from sklearn import datasets
iris = datasets.load_iris()

# A traditional approach: training a digit classifier and learning pyTorch tensors.

For this assignment, I ask you to read the Google Colab [04_mnist_basics.ipynb](https://colab.research.google.com/github/fastai/fastbook/blob/master/04_mnist_basics.ipynb#scrollTo=t1DK6o-gckCy) to the beginning of the chapter *Stochastic Gradient Descent (SGD)*. 

First, try to summarize what we know about pyTorch tensors by trying to predict whether we have a 1 or a 7 in the MNIST dataset using a traditional rule-based programming approach. Therefore use pyTorch tensors for the entire tasks and fulfill the following steps:

1) Randomly split the MNIST dataset (1 and 7) into a training dataset and a test dataset in a ratio of 80:20.

2) Instead of using an optimal 1 or 7 with the mean over the training dataset, try to calculate the sum of the distances to all instances in the training set for each instance in the test dataset. You can use the L2 norm. 

3) For each instance in the test set, decide if it is a 1 or 7 and calculate the precision.

Do we get a similar good result?


Number 1

In [ ]:
path.ls()

(#2) [Path('training'),Path('testing')]

In [ ]:
from sklearn.model_selection import train_test_split

path = untar_data(URLs.MNIST)
Path.BASE_PATH = path
path.ls()

(path/'training').ls()

ones = (path/'training'/'1').ls().sorted()
sevens = (path/'training'/'7').ls().sorted()



Showing an example of a one

In [ ]:
im3_path = ones[500]
im3 = Image.open(im3_path)
im3

Showing an example of a seven

In [ ]:
im3_path = sevens[500]
im3 = Image.open(im3_path)
im3

Splitting the test-train set

In [ ]:
train_set_ones, test_set_ones = train_test_split(ones, test_size=0.2,random_state=42)
train_set_sevens, test_set_sevens = train_test_split(sevens, test_size=0.2,random_state=42)




Number 2

In [ ]:
train_set_ones_tensor = [tensor(Image.open(o)) for o in train_set_ones]
stacked_train_set_ones_tensor = torch.stack(train_set_ones_tensor).float()/255

test_set_ones_tensor = [tensor(Image.open(o)) for o in test_set_ones]
stacked_test_set_ones_tensor = torch.stack(test_set_ones_tensor).float()/255


train_set_sevens_tensor = [tensor(Image.open(o)) for o in train_set_sevens]
stacked_train_set_sevens_tensor = torch.stack(train_set_sevens_tensor).float()/255


test_set_sevens_tensor = [tensor(Image.open(o)) for o in test_set_sevens]
stacked_test_set_sevens_tensor = torch.stack(test_set_sevens_tensor).float()/255


In [ ]:
def mnist_distance(a,b): return (a-b).abs().mean((-1,-2))

Number 3

In [ ]:
len(stacked_train_set_sevens_tensor)


5012

In [ ]:
len(stacked_train_set_ones_tensor)

5393

In [ ]:
import torch


amount_ones = 0
amount_sevens = 0

def is_one(test_instance, train_set):
    if is_one(test_instance, stacked_train_set_ones_tensor).sum() < mnist_distance(test_instance, stacked_train_set_sevens_tensor).sum():
      return 1
    else:
      return 7

for i in stacked_test_set_ones_tensor:
  if is_one(i, stacked_test_set_ones_tensor) == 1:
    amount_ones += 1


for j in stacked_test_set_sevens_tensor:
  if is_one(j, stacked_test_set_sevens_tensor) == 7:
    amount_sevens += 1

print(amount_ones)
print(amount_sevens)

accuracy_1s = is_one(amount_ones).float() .mean()
accuracy_7s = (1 - is_one(amount_sevens).float()).mean()

accuracy_1s,accuracy_7s,(accuracy_1s+accuracy_7s)/2







RecursionError: ignored

# Stochastic Gradient Descent (SGD)

For this exercise I ask you to read the chapter Stochastic Gradient Descent (SGD) from the Google Colab 04_mnist_basics.ipynb in paralell. The chapter starts with a single TLU, compare p. 304 in "Hands on Machine Learning". Go through all 7 steps which are an easy example of how Stochastic Gradient Descent works.

Our goal is to train a single TLU, which can decide if one number is larger then the other one. Therefore we create 100 random pairs with pyTorch and create a target vector which is eather 1 or 0.


In [ ]:
x = torch.randn((100, 2))
y = torch.where(x[:,0] > x[:,1], 1.0, 0.0)
print(x)
print(y)

tensor([[ 1.7878, -0.4780],
        [-0.2429, -0.9342],
        [-0.2483, -1.2082],
        [-0.4777,  0.5201],
        [-1.5673, -0.2394],
        [ 2.3228, -0.9634],
        [ 2.0024,  0.4664],
        [ 1.5730, -0.9228],
        [ 0.3559, -0.6866],
        [-0.4934,  0.2415],
        [-1.1109,  0.0915],
        [-2.3169, -0.2168],
        [-0.3097, -0.3957],
        [ 0.8034, -0.6216],
        [-0.5920, -0.0631],
        [-0.8286,  0.3309],
        [ 0.0349,  0.3211],
        [ 1.5736, -0.8455],
        [ 1.3123,  0.6872],
        [-1.0892, -0.3553],
        [-1.4181,  0.8963],
        [ 0.0499,  2.2667],
        [ 1.1790, -0.4345],
        [-1.3864, -1.2862],
        [-0.8371, -0.9224],
        [ 1.8113,  0.1606],
        [ 0.3672,  0.1754],
        [ 1.3852, -0.4459],
        [-1.2024,  0.7078],
        [-1.0759,  0.5357],
        [ 1.1754,  0.5612],
        [-0.4527, -0.7718],
        [ 0.1453,  0.2311],
        [ 0.0087, -0.1423],
        [ 0.1971, -1.1441],
        [ 0.3383,  1

Your task is to create a function f that is a single TLU, meaning that it summarizes x with weights a, b, c:

$ax_0+bx_1+c$

In Addition we are using a *sigmoid()* function as step function.

$f = \text{sigmoid}(ax_0+bx_1+c)$

In [ ]:
def f(x, params):
    a,b,c = params
    return 1 / (1 + torch.exp(-(a*x[:,0] + b*x[:,1] + c)))

print(f(x, [3,-2,1]))

tensor([9.9934e-01, 8.9471e-01, 9.3533e-01, 1.8645e-01, 3.8306e-02, 9.9995e-01, 9.9770e-01, 9.9948e-01, 9.6896e-01, 2.7627e-01, 7.4758e-02, 4.0012e-03, 7.0313e-01, 9.9056e-01, 3.4302e-01, 1.0457e-01,
        6.1361e-01, 9.9940e-01, 9.7242e-01, 1.7408e-01, 6.3893e-03, 3.2808e-02, 9.9553e-01, 3.5740e-01, 5.8259e-01, 9.9779e-01, 8.5207e-01, 9.9764e-01, 1.7585e-02, 3.5607e-02, 9.6782e-01, 7.6590e-01,
        7.2590e-01, 7.8760e-01, 9.7976e-01, 2.0047e-01, 9.9984e-01, 4.5356e-01, 5.7005e-02, 1.8816e-03, 9.9010e-01, 6.1393e-02, 9.9278e-01, 1.9120e-01, 1.0628e-01, 9.8876e-01, 9.9987e-01, 6.3458e-01,
        1.0112e-01, 9.0708e-01, 2.4475e-01, 7.6492e-02, 9.9221e-02, 6.9318e-01, 5.0639e-01, 9.9997e-01, 9.9594e-01, 9.9100e-01, 8.5539e-01, 4.0112e-01, 1.5012e-01, 6.3609e-01, 9.4963e-01, 8.9632e-01,
        5.0961e-01, 3.9711e-01, 9.9144e-01, 4.5663e-02, 8.5144e-01, 1.0271e-01, 3.0984e-01, 1.2615e-02, 9.9278e-01, 1.0321e-03, 9.1661e-01, 2.9208e-01, 6.7732e-01, 8.8517e-02, 4.8525e-03, 9.9753e-01,


In addition to our TLU function, we need a loss function. Your task is to implement a absolute difference loss function, $∑|x_i-y_i|$, which counts the number of wrong guesses.

In [ ]:
def mae(preds, targets): return (preds-targets).abs().mean()

Try to train your single TLU with the absolute difference loss function, use the following code. Choose an appropriate step weight `lr` and try to explain what is happing in each line.

lr = 1 : initializing a learning rate with the value 1.

params = torch.randn(3).requires_grad_(): initializing a tensor with random values from a normal distribution. 

def apply_step(params, prn=True): defining the function apply_step, the functions takes the tensor params as input, and a Boolean varaible prn.

preds = f(x, params): computes the predicted output of the model with the function f with the input tensor x and tensor pramas.

loss = mae(preds, y): Mean absolute error between predicted output and the true output y. 

loss.backward(): gradient of the loss

params.data -= lr * params.grad.data: updating the tensor prams.it subtracts the the product of the lr and the gradient of pramas.

params.grad = None: clears gradients of pramas.

if prn: print(params);print(loss.item()): prints parameter values and current loss if prn= True.

return preds: returns predicted output tensor preds.

for i in range(50): apply_step(params): applies apply_step function 50 times. 

In [ ]:
lr = 1
params = torch.randn(3).requires_grad_()

def apply_step(params, prn=True):
    preds = f(x, params)
    loss = mae(preds, y)
    loss.backward()
    params.data -= lr * params.grad.data
    params.grad = None
    if prn: print(params);print(loss.item())
    return preds


for i in range(50): apply_step(params)

tensor([0.3962, 0.1375, 0.0117], requires_grad=True)
0.4885903298854828
tensor([ 0.5515,  0.0276, -0.0099], requires_grad=True)
0.44941380620002747
tensor([ 0.6927, -0.0802, -0.0315], requires_grad=True)
0.41392049193382263
tensor([ 0.8193, -0.1844, -0.0521], requires_grad=True)
0.38309672474861145
tensor([ 0.9325, -0.2842, -0.0714], requires_grad=True)
0.3568616807460785
tensor([ 1.0339, -0.3794, -0.0892], requires_grad=True)
0.33462992310523987
tensor([ 1.1252, -0.4701, -0.1054], requires_grad=True)
0.3157126009464264
tensor([ 1.2080, -0.5565, -0.1200], requires_grad=True)
0.29948994517326355
tensor([ 1.2835, -0.6388, -0.1332], requires_grad=True)
0.2854542136192322
tensor([ 1.3529, -0.7173, -0.1450], requires_grad=True)
0.2732030749320984
tensor([ 1.4170, -0.7922, -0.1556], requires_grad=True)
0.2624201476573944
tensor([ 1.4765, -0.8640, -0.1651], requires_grad=True)
0.2528561055660248
tensor([ 1.5320, -0.9327, -0.1736], requires_grad=True)
0.2443130910396576
tensor([ 1.5841, -0.998

Write a line of code that counts the number of wrong predictions, rounding your predictions with *round()*.

In [ ]:
preds = f(x, params)
wrong_predictions = ((preds.round() - y).abs()).sum()
wrong_predictions


tensor(5., grad_fn=<SumBackward0>)